# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LSTJavaScriptCoreTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LSTJavaScriptCoreTest

  target 'LSTJavaScriptCoreTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LSTJavaScriptCoreTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'MJExtension'
pod 'MJRefresh'
pod 'WebViewJavascriptBridge'

end
